# Generated by Django 5.2.10 on 2026-01-25 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_achievments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievments",
            options={
                "ordering": ("id",),
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AlterModelOptions(
            name="projects",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Обновлено"
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Обновлено"
            ),
        ),
        migrations.AlterField(
            model_name="achievments",
            name="text",
            field=models.TextField(verbose_name="Достижение"),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(verbose_name="Текст новости"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(verbose_name="Описание проекта"),
        ),
    ]
