# Generated by Django 5.2.10 on 2026-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_rename_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "skills",
                    models.CharField(blank=True, max_length=200, verbose_name="Навыки"),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Участник команды",
                "verbose_name_plural": "Команда",
                "ordering": ("order", "name"),
            },
        ),
    ]
