# Generated by Django 5.2.10 on 2026-01-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0009_make_slugs_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
        ),
    ]
